version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: products_db
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend-products-management-api/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - products_network

  # Backend Node.js
  backend:
    build:
      context: ./backend-products-management-api
      dockerfile: Dockerfile
    container_name: products_backend
    environment:
      NODE_ENV: production
      PORT: 8001
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: products_db
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - products_network
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ./front-products-management
      dockerfile: Dockerfile
    container_name: products_frontend
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:8001/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - products_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  products_network:
    driver: bridge
